MODEL:
  WEIGHT: ""
  ARCHITECTURE: "CCA"
  CCA:
    NUM_CLIPS: 64
    FEATPOOL:
      INPUT_SIZE: 500
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 2
    FEAT2D:
      POOLING_COUNTS: [15,8,8]
    INTEGRATOR:
      QUERY_HIDDEN_SIZE: 512
      LSTM:
        NUM_LAYERS: 3
        BIDIRECTIONAL: True
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 9
      NUM_STACK_LAYERS: 4
    LOSS:
      MIN_IOU: 0.5
      MAX_IOU: 1.0
DATASETS:
  TRAIN: ("activitynet_train",)
  TEST: ("activitynet_test",)
INPUT:
  NUM_PRE_CLIPS: 512
  PRE_QUERY_SIZE: 300
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  LR: 0.0001
  BATCH_SIZE: 32
  MILESTONES: (10,20)
  MAX_EPOCH: 30
TEST:
  BATCH_SIZE: 64
  NMS_THRESH: 0.49
num_attribute: 3152
input_channel: 300
embed_size: 512
adj_file: ./acnet_concept/acnet_concept_adj.pkl
norm_func_type: sigmoid
inp_name: ./acnet_concept/acnet_concepts_glove_word2vec.pkl
concept_name: ./acnet_concept/acnet_category_concepts.json
com_concept: ./acnet_concept/acnet_com_graph.pkl
com_emb: ./acnet_concept/acnet_test_concepts.pkl
num_path: ./acnet_concept/acnet_dict.pkl